name = "nexnet-relay"
main = "src/index.ts"
compatibility_date = "2026-01-01"

[[durable_objects.bindings]]
name = "RELAY"
class_name = "RelaySession"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RelaySession"]
